name: "Get Server Version"
description: "Load latest working stable server version"

inputs:
  force:
    description: "Version Override"
    required: false

outputs:
  version:
    description: "Etebase Version"
    value: ${{ steps.get_version_file.outputs.version }}

runs:
  using: "composite"
  steps:
    - id: get_version_file
      shell: bash
      env:
        OVERRIDE: ${{ inputs.force }}
      run: |
        source server_version

        if [ ! -z "${OVERRIDE}" ]; then
          ETESYNC_VERSION="${OVERRIDE}"
        fi

        echo ::set-output name=version::${ETESYNC_VERSION}
