---
name: Call Build and Push

on:
  workflow_call:
    inputs:
      flavor:
        description: "Set the base image [base, slim or alpine]"
        default: "base"
        required: false
        type: string
      version:
        description: "EteBase Version"
        required: false
        type: string
      platforms:
        description: "Set the platforms to build [ linux/amd64, linux/arm64 or linux/arm/v7 ]"
        default: "linux/amd64,linux/arm64,linux/arm/v7"
        required: false
        type: string
      tag:
        description: "Tag"
        required: false
        type: string
      pushit:
        description: "Should push?"
        default: false
        required: false
        type: boolean
    secrets:
      dckr_username:
        required: true
      dckr_token:
        required: true

jobs:
  build-n-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dockerfiles and Context
        uses: actions/checkout@v3

      - id: server_version
        name: Get Server Version
        uses: ./.github/actions/get-server-version
        with:
          force: ${{ inputs.version }}

      - id: build_metadata
        name: Prepare Project Metadata
        uses: ./.github/actions/build-metadata
        with:
          flavor: ${{ inputs.flavor }}
          version: ${{ steps.server_version.outputs.version }}

      - id: docker_metadata
        name: Prepare Docker Metadata
        uses: docker/metadata-action@v3.8.0
        with:
          labels: |
            maintainer=victor-rds
            version=${{ steps.build_metadata.outputs.label_version }}
            org.opencontainers.image.authors=Victor R. Santos <victor-rds@users.noreply.github.com>
            org.opencontainers.image.title=Docker Etebase Server
            org.opencontainers.image.base.name=${{ steps.build_metadata.outputs.base_version }}
          images: |
            victorrds/etebase
            victorrds/etesync
          flavor: |
            latest=${{ ( inputs.flavor == 'base' && steps.build_metadata.outputs.semver == 'true' ) }}
            suffix=${{ steps.build_metadata.outputs.suffix }}
          tags: |
            type=edge,enable=${{ inputs.tag == 'edge' }},branch=${{ steps.build_metadata.outputs.source_name }}
            type=raw,value=${{ inputs.tag }},enable=${{ inputs.tag != '' && inputs.tag != 'edge' }}
            type=raw,value=${{ inputs.flavor }},suffix=,enable=${{ steps.build_metadata.outputs.semver == 'true' }}
            type=semver,pattern={{version}},value=${{ steps.build_metadata.outputs.ete_version }},enable=${{ inputs.tag == '' && steps.build_metadata.outputs.semver == 'true' }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.build_metadata.outputs.ete_version }},enable=${{ inputs.tag == '' && steps.build_metadata.outputs.semver == 'true' }}

      - name: Set up QEMU
        if: contains(inputs.platforms, 'linux/arm')
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.7.0

      - name: Login to DockerHub
        if: inputs.pushit
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.dckr_username }}
          password: ${{ secrets.dckr_token }}

      - name: Docker Build and Push
        id: docker_build_push
        uses: docker/build-push-action@v2.10.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          platforms: ${{ inputs.platforms }}
          context: .
          file: ./tags/${{ inputs.flavor }}/Dockerfile
          build-args: ETE_VERSION=${{ steps.build_metadata.outputs.ete_version }}
          tags: ${{ steps.docker_metadata.outputs.tags }}
          labels: ${{ steps.docker_metadata.outputs.labels }}
          push: ${{ inputs.pushit }}
