name: Build Base Tag on Pull Requests 

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'context/**'
      - 'tags/base/Dockerfile'
      - '.github/workflows/*-base.yml'

jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: victorrds/etesync
        always_pull: true
        push: false
        dockerfile: ./tags/base/Dockerfile
        tags: ${{ github.sha }}
        build_args: TAG=master