name: Build and Push Slim Tags

on:
  push:
    branches: [ release ]
    paths:
      - 'context/**'
      - 'tags/slim/Dockerfile'
      - '.github/workflows/release-slim.yml'
      
jobs:
  build-master:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'release'
    - uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: victorrds/etesync
        always_pull: true
        add_git_labels: true
        push: true
        dockerfile: ./tags/slim/Dockerfile
        tags: slim
        build_args: TAG=master

  build-v030:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'release'
    - uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: victorrds/etesync
        always_pull: true
        add_git_labels: true
        push: true
        dockerfile: ./tags/slim/Dockerfile
        tags: 0.3.0-slim
        build_args: TAG=v0.3.0