---
name: Test Metadata Actions for Dispatch Build

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Ref to Checkout"
        required: false
        default: "master"
      flavor:
        description: "Set the base image [base, slim or alpine]"
        required: false
        default: "base"
      version:
        description: "EteBase Version"
        required: false
        default: "master"
      platforms:
        description: "Set the platforms to build [ linux/amd64, linux/arm64 or linux/arm/v7 ]"
        required: false
        default: "linux/amd64,linux/arm64,linux/arm/v7"
      tag:
        description: "Tag"
        required: false
        default: ""
      pushit:
        description: "Should push?"
        required: false
        default: "false"

jobs:
  test-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dockerfiles and Context
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}

      - id: server_version
        uses: ./.github/actions/get-server-version
        with:
          force: ${{ github.event.inputs.version }}

      - id: build_metadata
        uses: ./.github/actions/build-metadata
        with:
          flavor: ${{ github.event.inputs.flavor }}
          version: ${{ steps.server_version.outputs.version }}

      - id: docker_metadata
        uses: docker/metadata-action@v3.6.2
        with:
          labels: |
            maintainer=victor-rds
            version=${{ steps.build_metadata.outputs.dckr_version }}
            org.opencontainers.image.authors=Victor R. Santos <victor-rds@users.noreply.github.com>
            org.opencontainers.image.title=Docker Etebase Server
            org.opencontainers.image.base.name=${{ steps.build_metadata.outputs.base_version }}
          images: |
            victorrds/etebase
            victorrds/etesync
          flavor: |
            latest=${{ ( github.event.inputs.flavor == 'base' && steps.build_metadata.outputs.semver == 'true' ) }}
            suffix=${{ steps.build_metadata.outputs.suffix }}
          tags: |
            type=edge,enable=${{ github.event.inputs.tag == 'edge' }},branch=${{ steps.build_metadata.outputs.source_name }}
            type=raw,value=${{ github.event.inputs.tag }},enable=${{ github.event.inputs.tag != '' && github.event.inputs.tag != 'edge' }}
            type=raw,value=${{ github.event.inputs.flavor }},suffix=,enable=${{ github.event.inputs.tag == '' && steps.build_metadata.outputs.semver == 'true' }}
            type=semver,pattern={{version}},value=${{ steps.build_metadata.outputs.ete_version }},enable=${{ github.event.inputs.tag == '' && steps.build_metadata.outputs.semver == 'true' }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.build_metadata.outputs.ete_version }},enable=${{ github.event.inputs.tag == '' && steps.build_metadata.outputs.semver == 'true' }}
