---
name: Trigger Builds

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Ref to Checkout"
        required: false
        default: "release"
      version:
        description: "EteBase Version"
        required: false
        default: ""
      platforms:
        description: "Set the platforms to build [ linux/amd64, linux/arm64 or linux/arm/v7 ]"
        required: false
        default: "linux/amd64,linux/arm64,linux/arm/v7"
      pushit:
        description: "Should push?"
        required: false
        default: "false"
      tag:
        description: "Tag"
        required: true
        default: ""

jobs:
  trigger-builds:
    runs-on: ubuntu-latest
    env:
      WORKFLOW: Build and Push

    steps:
      - id: server_version
        uses: ./.github/actions/get-server-version
        with:
          force: ${{ github.event.inputs.version }}

      - id: generate-inputs
        name: Cast value to JSON to preserve Boolean
        env:
          JSON_INPUT: >-
            "ref": "${{ github.event.inputs.ref }}",
            "pushit": "${{ github.event.inputs.pushit }}",
            "tag": "${{ github.event.inputs.tag }}",
            "version": "${{ steps.server_version.outputs.version }}",
            "platforms": "${{ github.event.inputs.platforms }}"'
        shell: bash
        run: |
          readonly JSON_START='${{ env.JSON_INPUT }}'

          base_inputs="{ ${JSON_START}, \"flavor\": \"base\" }"
          slim_inputs="{ ${JSON_START}, \"flavor\": \"slim\" }"
          alpine_inputs="{ ${JSON_START}, \"flavor\": \"alpine\" }"

          echo ::set-output name=base_inputs::${base_inputs}
          echo ::set-output name=slim_inputs::${slim_inputs}
          echo ::set-output name=alpine_inputs::${alpine_inputs}

      - name: Invoke workflow Build and Push for Base tag
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: ${{ env.WORKFLOW }}
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: ${{ steps.generate-inputs.outputs.base_inputs }}

      - name: Invoke workflow Build and Push for Slim tag
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: ${{ env.WORKFLOW }}
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: ${{ steps.generate-inputs.outputs.slim_inputs }}

      - name: Invoke workflow Build and Push for Alpine taf
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: ${{ env.WORKFLOW }}
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: ${{ steps.generate-inputs.outputs.alpine_inputs }}
