---
name: Trigger Edge Builds

on:
  push:
    branches:
      - release
    paths:
      - "context/**"
      - "tags/**/Dockerfile"
      - ".github/workflows/dispatch-build.yml"
      - ".github/workflows/trigger-edge.yml"

jobs:
  trigger-builds:
    runs-on: ubuntu-latest
    env:
      WORKFLOW: Build and Push

    steps:
      - id: generate-inputs
        name: Cast value to JSON to preserve Boolean
        env:
          JSON_INPUT: >- 
            "ref": "release",
            "version": "master",
            "pushit": "true",
            "platforms": "linux/amd64,linux/arm64,linux/arm/v7",
            "tag": "edge"
        shell: bash
        run: |
          readonly JSON_START='${{ env.JSON_INPUT }}'         

          base_inputs="{ ${JSON_START}, \"flavor\": \"base\" }"
          slim_inputs="{ ${JSON_START}, \"flavor\": \"slim\" }"
          alpine_inputs="{ ${JSON_START}, \"flavor\": \"alpine\" }"

          echo ::set-output name=base_inputs::${base_inputs}
          echo ::set-output name=slim_inputs::${slim_inputs}
          echo ::set-output name=alpine_inputs::${alpine_inputs}

      - name: Invoke workflow Build and Push for Base tag
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: ${{ env.WORKFLOW }}
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: ${{ steps.generate-inputs.outputs.base_inputs }}

      - name: Invoke workflow Build and Push for Slim tag
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: ${{ env.WORKFLOW }}
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: ${{ steps.generate-inputs.outputs.slim_inputs }}

      - name: Invoke workflow Build and Push for Alpine taf
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: ${{ env.WORKFLOW }}
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: ${{ steps.generate-inputs.outputs.alpine_inputs }}
